# Generated by Django 2.1.1 on 2018-11-08 03:49

from django.db import migrations

def forwards_func(apps, schema_editor):
    Task = apps.get_model("Download9", "task")
    db_alias = schema_editor.connection.alias
    Task.objects.using(db_alias).all().delete()


def reverse_func(apps, schema_editor):
    Task = apps.get_model("Download9", "task")
    db_alias = schema_editor.connection.alias
    Task.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Download9', '0004_auto_20181108_1108'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
