# Generated by Django 2.1.3 on 2018-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download9', '0005_auto_20181108_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createtime',
            field=models.CharField(default='2018-01-01', max_length=10),
        ),
    ]
