# Generated by Django 2.1.3 on 2019-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download9', '0006_task_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='memoryused',
            field=models.IntegerField(default=0),
        ),
    ]
