# Generated by Django 2.1.1 on 2018-11-05 16:09

from django.db import migrations
import json, os
from Download9.getmd5 import getmd5
from Download9.models import *

testaccountjson = open(os.path.join(os.path.dirname(__file__), 'testaccount.json'), 'r', encoding='utf8')
testaccount = json.load(testaccountjson)
req = []
for x in testaccount:
    print(getmd5(x["password"]))
    req.append(account(username=x["username"], password=getmd5(x["password"])))

def forwards_func(apps, schema_editor):
    Account = apps.get_model("Download9", "account")
    db_alias = schema_editor.connection.alias
    Account.objects.using(db_alias).bulk_create(req)


def reverse_func(apps, schema_editor):
    Account = apps.get_model("Download9", "account")
    db_alias = schema_editor.connection.alias
    Account.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Download9', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
