# Generated by Django 2.1.1 on 2018-11-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download9', '0002_auto_20181106_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('gid', models.CharField(max_length=40)),
                ('taskname', models.CharField(max_length=40)),
            ],
        ),
    ]
